### ISSUE TITLE
Illegal char <:> at index 35: D:\code\node\deps\uv\src\win\util.c:620

### ISSUE THREAD

**Issue by refack** [johnthagen/clion-cppcheck#7]
### Environment

* Operating System (e.g. Ubuntu 16.04 x64): `Windows 10x64 build 15063.483`
* IDE Version (e.g. CLion 2016.3.2): `PyCharm 2017.2 Build #PY-172.3317.86, built on July 19, 2017`
* Cppcheck executable version (`cppcheck --version`): `Cppcheck 1.79`
* Cppcheck plugin version: `1.0.7`
* Exact strings used in cppcheck plugin options:
  * **cppcheck path**: `C:\bin\dev\Cppcheck\cppcheck.exe`
  * **cppcheck options**: `--enable=warning,performance,portability,style`

### Expected behaviour
Not throw exceptions 😉 

### Actual behaviour
Throws:
```
Illegal char <:> at index 35: D:\code\node\deps\uv\src\win\util.c:620] -> [D:\code\node\deps\uv\src\win\util.c
java.nio.file.InvalidPathException: Illegal char <:> at index 35: D:\code\node\deps\uv\src\win\util.c:620] -> [D:\code\node\deps\uv\src\win\util.c
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at com.github.johnthagen.cppcheck.CppcheckInspection.checkFile(CppcheckInspection.java:80)
	at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:156)
	at com.intellij.psi.PsiElementVisitor.visitPlainTextFile(PsiElementVisitor.java:42)
	at com.intellij.psi.impl.source.PsiPlainTextFileImpl.accept(PsiPlainTextFileImpl.java:36)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:82)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:305)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:250)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

### Steps to reproduce the behaviour
checkout `node` from https://github.com/nodejs/node
open `deps\uv\src\win\util.c`

**Comment by johnthagen** [comment]
Hmm, it looks like it's because of the `D:` (specifically the `:`). I assume PyCharm is running from `C:`?

If you move the files that Cppcheck is running against to `C:`, does it still throw the exception?

**Comment by refack** [comment]
Yep (PyCharm, Cppcheck and code are all on C:)
But to me it seems like it borkes on the line separator
```
C:\temp\node6\deps\uv\src\win\util.c:609] -> [C:\temp\node6\deps\
                                    ^index 36
```
```Java
Illegal char <:> at index 36: C:\temp\node6\deps\uv\src\win\util.c:609] -> [C:\temp\node6\deps\uv\src\win\util.c
java.nio.file.InvalidPathException: Illegal char <:> at index 36: C:\temp\node6\deps\uv\src\win\util.c:609] -> [C:\temp\node6\deps\uv\src\win\util.c
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at com.github.johnthagen.cppcheck.CppcheckInspection.checkFile(CppcheckInspection.java:80)
	at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:156)
	at com.intellij.psi.PsiElementVisitor.visitPlainTextFile(PsiElementVisitor.java:42)
	at com.intellij.psi.impl.source.PsiPlainTextFileImpl.accept(PsiPlainTextFileImpl.java:36)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:82)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:305)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1155)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:250)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecCC(ForkJoinPool.java:1190)
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1879)
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2045)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:390)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2616)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:63)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:57)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:316)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:226)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:132)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:250)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by johnthagen** [comment]
Yeah, probably something wrong with the regex that this case is failing on: https://github.com/johnthagen/clion-cppcheck/blob/master/src/com/github/johnthagen/cppcheck/CppcheckInspection.java#L69

**Comment by refack** [comment]
It seems like my line does not start with `[` 😕 
I'll try to get the raw Cppcheck output.
BTW: it works for other files in that same directory, just `util.c` gives it trouble.

**Comment by refack** [comment]
```
C:\temp\node6\deps\uv\src\win$ C:\bin\dev\Cppcheck\cppcheck.exe --enable=warning,performance,portability,style C:\temp\node6\deps\uv\src\win\util.c
Checking C:\temp\node6\deps\uv\src\win\util.c ...
[C:\temp\node6\deps\uv\src\win\util.c:650]: (portability) %d in format string (no. 1) requires 'int' but the argument type is 'DWORD {aka unsigned long}'.
[C:\temp\node6\deps\uv\src\win\util.c:609] -> [C:\temp\node6\deps\uv\src\win\util.c:615]: (style) Variable 'cpu_count' is reassigned a value before the old one has been used.
[C:\temp\node6\deps\uv\src\win\util.c:218]: (style) The scope of the variable 'env_var' can be reduced.
Checking C:\temp\node6\deps\uv\src\win\util.c: NTSTATUS_FROM_WIN32...
Checking C:\temp\node6\deps\uv\src\win\util.c: _DEBUG...
Checking C:\temp\node6\deps\uv\src\win\util.c: _MSC_VER...
Checking C:\temp\node6\deps\uv\src\win\util.c: _MSC_VER;__MINGW64_VERSION_MAJOR...
Checking C:\temp\node6\deps\uv\src\win\util.c: _MSC_VER;snprintf...
Checking C:\temp\node6\deps\uv\src\win\util.c: _WIN32...
Checking C:\temp\node6\deps\uv\src\win\util.c: __MINGW32__;__MINGW64_VERSION_MAJOR...
```

While this one parses correctly:
```
C:\temp\node6\deps\uv\src\win$ C:\bin\dev\Cppcheck\cppcheck.exe --enable=warning,performance,portability,style C:\temp\node6\deps\uv\src\win\fs-event.c
Checking C:\temp\node6\deps\uv\src\win\fs-event.c ...
[C:\temp\node6\deps\uv\src\win\fs-event.c:505]: (style) Condition '!(handle->flags&UV__HANDLE_CLOSING)' is always true
[C:\temp\node6\deps\uv\src\win\fs-event.c:514]: (style) Condition '!(handle->flags&UV__HANDLE_CLOSING)' is always true
[C:\temp\node6\deps\uv\src\win\fs-event.c:366]: (style) The scope of the variable 'err' can be reduced.
[C:\temp\node6\deps\uv\src\win\fs-event.c:366]: (style) The scope of the variable 'sizew' can be reduced.
[C:\temp\node6\deps\uv\src\win\fs-event.c:366]: (style) The scope of the variable 'size' can be reduced.
Checking C:\temp\node6\deps\uv\src\win\fs-event.c: NTSTATUS_FROM_WIN32...
Checking C:\temp\node6\deps\uv\src\win\fs-event.c: _DEBUG...
Checking C:\temp\node6\deps\uv\src\win\fs-event.c: _MSC_VER...
Checking C:\temp\node6\deps\uv\src\win\fs-event.c: _MSC_VER;__MINGW64_VERSION_MAJOR...
Checking C:\temp\node6\deps\uv\src\win\fs-event.c: _MSC_VER;snprintf...
Checking C:\temp\node6\deps\uv\src\win\fs-event.c: _WIN32...
Checking C:\temp\node6\deps\uv\src\win\fs-event.c: __MINGW32__;__MINGW64_VERSION_MAJOR...
```

**Comment by johnthagen** [comment]
FWIW, bug still present with Cppchecck 1.80

**Comment by johnthagen** [comment]
The offending line:

```
[C:\Users\User\GitHub\node\deps\uv\src\win\util.c:620] -> [C:\Users\User\GitHub\node\deps\uv\src\win\util.c:626]: (style) Variable 'cpu_count' is reassigned a value before the old one has been used.
```

**Comment by johnthagen** [comment]
[v1.0.8](https://plugins.jetbrains.com/plugin/8143-cppcheck) has been released and once it's approved, please download and verify it fixes your problem.

**Comment by refack** [comment]
Confirmed 1.0.8 solves my issue.
10x!
